version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentinternportal
    volumes:
      - db_data:/var/lib/mysql
      - ./studentinternportal.sql:/docker-entrypoint-initdb.d/studentinternportal.sql
    restart: always

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: studentinternportal
    restart: always

volumes:
  db_data:
    name: sip_volume
